// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/qushot/clean-arcihtecture-idea/application/usecase/addtask"
	"github.com/qushot/clean-arcihtecture-idea/infrastructure/persistence/dummy"
	"github.com/qushot/clean-arcihtecture-idea/interfaces/controller"
	"github.com/qushot/clean-arcihtecture-idea/interfaces/presenter"
)

// Injectors from wire.go:

func InitializeApp() *controller.AddTask {
	repository := dummy.NewTaskRepository()
	outputPort := presenter.NewAddTask()
	inputPort := addtask.NewInteractor(repository, outputPort)
	addTask := controller.NewAddTask(inputPort)
	return addTask
}
